package com.verifolio.verification.domain

data class BadgeText(val title: String, val limitation: String?)

/** Plain-language badge texts mirroring docs/VERIFICATION_SIGNALS.md. */
object BadgeCatalog {

    private val catalog: Map<String, BadgeText> = mapOf(
        "EMAIL_CONFIRMED" to BadgeText(
            "Email address was confirmed.",
            "Email confirmation proves access to the mailbox, not identity or authority.",
        ),
        "CORPORATE_DOMAIN_CONFIRMED" to BadgeText(
            "Corporate domain was confirmed.",
            "Domain confirmation is a point-in-time check: it shows the email belonged to the domain when confirmed. " +
                "It does not prove current employment, and it does not prove the person is authorized to speak on behalf of the company.",
        ),
        "RECIPIENT_CONFIRMED" to BadgeText("Recommender confirmed the recipient.", null),
        "RECOMMENDER_RELATIONSHIP_CONFIRMED" to BadgeText(
            "Recommender stated and confirmed their relationship to the recipient.",
            "The relationship value is stated by the recommender.",
        ),
        "SCAN_ATTACHED" to BadgeText(
            "Source scan was attached.",
            "A scan can increase confidence but does not automatically prove authenticity.",
        ),
        "SIGNATURE_ATTACHED" to BadgeText("Digital signature file was attached.", null),
        "SIGNATURE_VERIFIED" to BadgeText(
            "The attached signature was verified.",
            "Signature verification covers only the uploaded signed file (the scan), not the PDF generated by Verifolio. " +
                "It does not independently guarantee that every statement in the document is true.",
        ),
        "VERSION_LOCKED" to BadgeText("Document version is locked.", null),
        "DOCUMENT_HASH_LOCKED" to BadgeText("Document hash was recorded.", null),
        "PUBLIC_VERIFICATION_ENABLED" to BadgeText("Public verification page is active.", null),
    )

    fun describe(signalType: String): BadgeText =
        catalog[signalType] ?: BadgeText(signalType, null)
}
