package com.verifolio.files.application

import com.verifolio.audit.AuditService
import com.verifolio.files.DownloadLink
import com.verifolio.files.FileStore
import com.verifolio.files.StoredFile
import com.verifolio.files.infrastructure.S3StorageAdapter
import com.verifolio.jooq.tables.references.FILE_OBJECT
import com.verifolio.platform.ApiException
import com.verifolio.platform.VerifolioProperties
import org.jooq.DSLContext
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.security.MessageDigest
import java.time.OffsetDateTime
import java.util.UUID

@Service
internal class FileStoreImpl(
    private val dsl: DSLContext,
    private val storage: S3StorageAdapter,
    private val audit: AuditService,
    private val props: VerifolioProperties,
) : FileStore {

    @Transactional
    override fun storeGeneratedPdf(
        ownerProfileId: UUID,
        documentId: UUID,
        versionId: UUID,
        filename: String,
        bytes: ByteArray,
    ): StoredFile {
        val fileId = UUID.randomUUID()
        // Opaque IDs only — never user-provided names or emails (docs/FILES_AND_STORAGE.md).
        val key = "${props.region}/$ownerProfileId/$documentId/$versionId/$fileId"
        val sha256 = sha256Hex(bytes)

        storage.put(key, bytes, "application/pdf")

        val fo = FILE_OBJECT
        dsl.insertInto(fo)
            .set(fo.ID, fileId)
            .set(fo.BUCKET, props.storage.bucket)
            .set(fo.STORAGE_KEY, key)
            .set(fo.ORIGINAL_FILENAME, filename)
            .set(fo.MIME_TYPE, "application/pdf")
            .set(fo.SIZE_BYTES, bytes.size.toLong())
            .set(fo.SHA256_HASH, sha256)
            .set(fo.PURPOSE, "GENERATED_PDF")
            // Backend-generated bytes skip the async validation pipeline (uploads only).
            .set(fo.STATUS, "READY")
            .set(fo.UPLOADED_BY_ACTOR_ID, "SYSTEM")
            .execute()

        audit.record(
            actorType = "SYSTEM",
            actorId = null,
            action = "FILE_UPLOADED",
            entityType = "FILE_OBJECT",
            entityId = fileId.toString(),
            metadata = mapOf("purpose" to "GENERATED_PDF", "sizeBytes" to bytes.size.toString()),
        )

        return StoredFile(fileId = fileId, sha256 = sha256, sizeBytes = bytes.size.toLong())
    }

    @Transactional(readOnly = true)
    override fun presignedDownloadUrl(fileId: UUID): DownloadLink {
        val fo = FILE_OBJECT
        val record = dsl.selectFrom(fo)
            .where(fo.ID.eq(fileId).and(fo.STATUS.eq("READY")))
            .fetchOne()
            ?: throw ApiException(HttpStatus.NOT_FOUND, "NOT_FOUND", "File not found")

        val ttl = props.storage.presignedTtl
        val url = storage.presignGet(record.storageKey!!, record.originalFilename!!, ttl)
        return DownloadLink(url = url, expiresAt = OffsetDateTime.now().plus(ttl))
    }

    private fun sha256Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
}
