package com.verifolio.files.application

import com.verifolio.audit.AuditService
import com.verifolio.files.DownloadLink
import com.verifolio.files.FileStore
import com.verifolio.files.StoredFile
import com.verifolio.files.infrastructure.S3StorageAdapter
import com.verifolio.jooq.tables.references.FILE_OBJECT
import com.verifolio.platform.ApiException
import com.verifolio.platform.VerifolioProperties
import org.jooq.DSLContext
import org.slf4j.LoggerFactory
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import org.springframework.transaction.support.TransactionSynchronization
import org.springframework.transaction.support.TransactionSynchronizationManager
import java.security.MessageDigest
import java.time.OffsetDateTime
import java.util.UUID

@Service
internal class FileStoreImpl(
    private val dsl: DSLContext,
    private val storage: S3StorageAdapter,
    private val audit: AuditService,
    private val props: VerifolioProperties,
) : FileStore {

    private val log = LoggerFactory.getLogger(FileStoreImpl::class.java)

    @Transactional
    override fun storeGeneratedPdf(
        ownerProfileId: UUID,
        documentId: UUID,
        versionId: UUID,
        filename: String,
        bytes: ByteArray,
    ): StoredFile {
        val fileId = UUID.randomUUID()
        // Opaque IDs only — never user-provided names or emails (docs/FILES_AND_STORAGE.md).
        val key = "${props.region}/$ownerProfileId/$documentId/$versionId/$fileId"
        val sha256 = sha256Hex(bytes)

        storage.put(key, bytes, "application/pdf")

        // Compensation: the S3 write is not transactional. If the surrounding transaction
        // rolls back (accept failure after the upload), delete the orphaned object so no
        // untracked user data remains in storage.
        TransactionSynchronizationManager.registerSynchronization(object : TransactionSynchronization {
            override fun afterCompletion(status: Int) {
                if (status == TransactionSynchronization.STATUS_ROLLED_BACK) {
                    runCatching { storage.delete(key) }
                        .onFailure { log.warn("Failed to clean up orphaned object {} after rollback", key, it) }
                }
            }
        })

        val fo = FILE_OBJECT
        dsl.insertInto(fo)
            .set(fo.ID, fileId)
            .set(fo.BUCKET, props.storage.bucket)
            .set(fo.STORAGE_KEY, key)
            .set(fo.ORIGINAL_FILENAME, filename)
            .set(fo.MIME_TYPE, "application/pdf")
            .set(fo.SIZE_BYTES, bytes.size.toLong())
            .set(fo.SHA256_HASH, sha256)
            .set(fo.PURPOSE, "GENERATED_PDF")
            // Backend-generated bytes skip the async validation pipeline (uploads only).
            .set(fo.STATUS, "READY")
            .set(fo.UPLOADED_BY_ACTOR_ID, "SYSTEM")
            .execute()

        audit.record(
            actorType = "SYSTEM",
            actorId = null,
            action = "FILE_UPLOADED",
            entityType = "FILE_OBJECT",
            entityId = fileId.toString(),
            metadata = mapOf("purpose" to "GENERATED_PDF", "sizeBytes" to bytes.size.toString()),
        )

        return StoredFile(fileId = fileId, sha256 = sha256, sizeBytes = bytes.size.toLong())
    }

    @Transactional
    override fun storeExport(bytes: ByteArray): StoredFile {
        val fileId = UUID.randomUUID()
        // Opaque region-scoped key — no subject identifiers in the path (docs/FILES_AND_STORAGE.md).
        val key = "${props.region}/exports/$fileId"
        val sha256 = sha256Hex(bytes)

        storage.put(key, bytes, "application/json")

        // Compensation: the S3 write is not transactional. If the surrounding transaction rolls
        // back, delete the orphaned object so no untracked subject data remains in storage.
        TransactionSynchronizationManager.registerSynchronization(object : TransactionSynchronization {
            override fun afterCompletion(status: Int) {
                if (status == TransactionSynchronization.STATUS_ROLLED_BACK) {
                    runCatching { storage.delete(key) }
                        .onFailure { log.warn("Failed to clean up orphaned export object {} after rollback", key, it) }
                }
            }
        })

        val fo = FILE_OBJECT
        dsl.insertInto(fo)
            .set(fo.ID, fileId)
            .set(fo.BUCKET, props.storage.bucket)
            .set(fo.STORAGE_KEY, key)
            .set(fo.ORIGINAL_FILENAME, "data-export.json")
            .set(fo.MIME_TYPE, "application/json")
            .set(fo.SIZE_BYTES, bytes.size.toLong())
            .set(fo.SHA256_HASH, sha256)
            .set(fo.PURPOSE, "DATA_EXPORT")
            // Backend-generated bytes skip the async validation pipeline (uploads only).
            .set(fo.STATUS, "READY")
            .set(fo.UPLOADED_BY_ACTOR_ID, "SYSTEM")
            .execute()

        audit.record(
            actorType = "SYSTEM",
            actorId = null,
            action = "FILE_UPLOADED",
            entityType = "FILE_OBJECT",
            entityId = fileId.toString(),
            metadata = mapOf("purpose" to "DATA_EXPORT", "sizeBytes" to bytes.size.toString()),
        )

        return StoredFile(fileId = fileId, sha256 = sha256, sizeBytes = bytes.size.toLong())
    }

    @Transactional(readOnly = true)
    override fun presignedDownloadUrl(fileId: UUID): DownloadLink =
        presignedDownloadUrl(fileId, props.storage.presignedTtl)

    @Transactional(readOnly = true)
    override fun presignedDownloadUrl(fileId: UUID, ttl: java.time.Duration): DownloadLink {
        val fo = FILE_OBJECT
        val record = dsl.selectFrom(fo)
            .where(fo.ID.eq(fileId).and(fo.STATUS.eq("READY")))
            .fetchOne()
            ?: throw ApiException(HttpStatus.NOT_FOUND, "NOT_FOUND", "File not found")

        val url = storage.presignGet(record.storageKey!!, record.originalFilename!!, ttl)
        return DownloadLink(url = url, expiresAt = OffsetDateTime.now().plus(ttl))
    }

    @Transactional
    override fun deleteGeneratedAsSystem(fileId: UUID) {
        val fo = FILE_OBJECT
        val record = dsl.selectFrom(fo).where(fo.ID.eq(fileId)).forUpdate().fetchOne() ?: return
        // Idempotent: an already-DELETED object is a no-op (tombstone re-runs land here).
        if (record.status == "DELETED") return
        // Storage first, DB status after (cleanup-task precedent). Swallow storage failure —
        // the object may already be gone; the row still flips to DELETED so it is never served.
        runCatching { storage.delete(record.storageKey!!) }
        dsl.update(fo)
            .set(fo.STATUS, "DELETED")
            .set(fo.DELETED_AT, OffsetDateTime.now())
            .where(fo.ID.eq(fileId))
            .execute()
        audit.record(
            actorType = "SYSTEM", actorId = null, action = "FILE_DELETED",
            entityType = "FILE_OBJECT", entityId = fileId.toString(),
            metadata = mapOf("purpose" to (record.purpose ?: "GENERATED_PDF")),
        )
    }

    private fun sha256Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
}
